version: '3.2'
services:

  app_producer:
    build:
        context: ./app_producer
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=demo.orders.new
    volumes:
        - ./app_producer:/go/src/app_producer

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
    depends_on:
      - zookeeper
    ports:
      - 29092:29092